### ISSUE TITLE
flight schedule

### ISSUE THREAD

**Issue by sam-8680** [anshuljain21120/Fleet_Routing_and_Assignment#2]
not able to understand objective function of problem 2 .
please explain it

**Comment by anshuljain21120** [comment]
Hi @sam-8680 !
Thanks for checking this repository. I did this problem in Nov of 2018 for my college, so unfortunately it is hard for me now to recall all those things. Anyway, I'll look into it soon and will add comments to explain that function properly.

Closing this comment with regards,
Anshul Jain

**Comment by 15761384682** [comment]
Is there a route map?
